name = "alt-label-tools"
compatibility_date = "2024-01-01"

# Build output directory for Astro
pages_build_output_dir = "dist"

# Environment variables
[vars]
NODE_ENV = "production"
PRODUCTION_URL = "https://alt-label-tools.pages.dev"
YARN_VERSION = "1"
NODE_VERSION = "22.14.0"
GOOGLE_SERVICE_ACCOUNT_EMAIL="alt-frontend@n8n-v2-454309.iam.gserviceaccount.com"

# Development configuration
[dev]
port = 8787
local_protocol = "http"
upstream_protocol = "http"

[[kv_namespaces]]
binding = "ALT_LABEL_TOOLS_SESSION"
id = "486f471ab5be48df802ef5cec49d9235"
preview_id = "0727860cf16d4f4b8e3ac66a1597472a" 