#!/usr/bin/env python3
"""
Test Release Creator with Real Files
Creates a complete test release using the generated audio files
"""

import sys
import os
from datetime import datetime
from config import *

# Import Supabase
try:
    from supabase import create_client, Client
except ImportError:
    print("❌ Supabase library not installed. Run: pip install supabase")
    sys.exit(1)

def create_test_release_with_files():
    """Create a test release with actual audio files."""
    
    try:
        # Connect to Supabase
        supabase: Client = create_client(SUPABASE_URL, SUPABASE_ANON_KEY)
        print("✅ Connected to Supabase")
        
        # Define file paths
        base_path = "C:/temp/bandcamp_test_music"
        audio_files = [
            f"{base_path}/track1_opening.wav",
            f"{base_path}/track2_middle.wav", 
            f"{base_path}/track3_finale.wav"
        ]
        
        # Verify files exist
        missing_files = []
        for file_path in audio_files:
            if not os.path.exists(file_path):
                missing_files.append(file_path)
        
        if missing_files:
            print("❌ Missing audio files:")
            for file in missing_files:
                print(f"   📁 {file}")
            print("\n💡 Run 'python create_test_audio.py' first to create test files")
            return False
        
        print("✅ All audio files found")
        
        # Create release data
        release_data = {
            "user_id": 1,
            "title": "Demo Album - Upload Test 2024", 
            "artist": "Automation Test Artist",
            "about": "This is a complete test album with real audio files created for testing the Bandcamp upload automation system. Features three sine wave tracks at different frequencies.",
            "credits": "Generated by: Bandcamp Upload Automation\nTesting Framework: Python + Selenium\nAudio Generation: Pure Python Sine Waves",
            "tags": "electronic, test, automation, demo, experimental",
            "price": 15.00,
            "name_your_price": True,
            "upload_status": "draft",
            "release_date": datetime.now().isoformat()
        }
        
        print("📀 Creating test release...")
        release_result = supabase.table("releases").insert(release_data).execute()
        
        if not release_result.data:
            print("❌ Failed to create release")
            return False
            
        release_id = release_result.data[0]["id"]
        print(f"✅ Release created with ID: {release_id}")
        
        # Create track data with real file paths and calculated file sizes
        tracks_data = []
        track_info = [
            ("Track 1 - Opening Movement", "The opening movement featuring a pure 440Hz sine wave - the musical note A4", audio_files[0]),
            ("Track 2 - Middle Exploration", "The middle movement exploring higher frequencies with a 523Hz sine wave - the musical note C5", audio_files[1]),
            ("Track 3 - Grand Finale", "The epic finale reaching even higher with a 659Hz sine wave - the musical note E5", audio_files[2])
        ]
        
        for i, (title, description, file_path) in enumerate(track_info, 1):
            file_size = os.path.getsize(file_path)
            file_name = os.path.basename(file_path)
            
            track_data = {
                "release_id": release_id,
                "title": title,
                "artist": "Automation Test Artist",
                "track_number": i,
                "file_path": file_path,
                "file_name": file_name,
                "file_size": file_size,
                "about": description,
                "credits": "Generated by Python sine wave algorithm",
                "upload_status": "pending",
                "duration": 30 if i == 1 else (25 if i == 2 else 35)  # Track durations
            }
            tracks_data.append(track_data)
        
        print("🎵 Creating tracks with file information...")
        tracks_result = supabase.table("tracks").insert(tracks_data).execute()
        
        if not tracks_result.data:
            print("❌ Failed to create tracks")
            return False
            
        print(f"✅ Created {len(tracks_result.data)} tracks")
        
        # Create upload session
        session_data = {
            "user_id": 1,
            "release_id": release_id,
            "session_status": "active",
            "total_tracks": len(tracks_data),
            "uploaded_tracks": 0,
            "failed_tracks": 0,
            "started_at": datetime.now().isoformat()
        }
        
        print("📊 Creating upload session...")
        session_result = supabase.table("upload_sessions").insert(session_data).execute()
        
        if not session_result.data:
            print("❌ Failed to create upload session")
            return False
            
        session_id = session_result.data[0]["id"]
        print(f"✅ Upload session created with ID: {session_id}")
        
        # Display summary
        print("\n" + "="*60)
        print("🎉 TEST RELEASE CREATED SUCCESSFULLY!")
        print("="*60)
        print(f"📀 Release: '{release_data['title']}'")
        print(f"🎤 Artist: {release_data['artist']}")
        print(f"🎵 Tracks: {len(tracks_data)}")
        print(f"📊 Session ID: {session_id}")
        print(f"💰 Price: ${release_data['price']}")
        
        print("\n📁 Audio Files:")
        total_size = 0
        for i, track in enumerate(tracks_result.data, 1):
            file_size = track.get('file_size', 0)
            total_size += file_size
            print(f"   {i}. {track['title']}")
            print(f"      📁 {track['file_path']}")
            print(f"      📊 {file_size:,} bytes ({file_size/1024/1024:.1f} MB)")
        
        print(f"\n📊 Total audio size: {total_size:,} bytes ({total_size/1024/1024:.1f} MB)")
        
        print("\n🚀 READY FOR UPLOAD TEST!")
        print("="*60)
        print("Next step: Run the upload automation:")
        print(f"   python bandcamp_automation.py --upload --user-id 1")
        print("\nWhat will happen:")
        print("1. 🔐 Login to Bandcamp (CAPTCHA may appear)")
        print("2. 📝 Fill album details from database")
        print("3. 📤 Upload each audio file")
        print("4. 🎵 Fill track metadata")
        print("5. 💾 Save the complete release")
        print("6. 📊 Update database with results")
        
        return True
        
    except Exception as e:
        print(f"❌ Error creating test release: {e}")
        return False

def verify_files():
    """Verify that all required files exist."""
    base_path = "C:/temp/bandcamp_test_music"
    required_files = [
        "track1_opening.wav",
        "track2_middle.wav", 
        "track3_finale.wav"
    ]
    
    print("🔍 Verifying test files...")
    all_exist = True
    
    for filename in required_files:
        filepath = f"{base_path}/{filename}"
        if os.path.exists(filepath):
            size = os.path.getsize(filepath)
            print(f"   ✅ {filename} ({size:,} bytes)")
        else:
            print(f"   ❌ {filename} - NOT FOUND")
            all_exist = False
    
    return all_exist

if __name__ == "__main__":
    print("🧪 Bandcamp Test Release Creator")
    print("🔗 Connecting to Supabase...")
    
    # First verify files exist
    if not verify_files():
        print("\n❌ Missing test files!")
        print("💡 Run 'python create_test_audio.py' first")
        sys.exit(1)
    
    # Create the test release
    success = create_test_release_with_files()
    
    if not success:
        print("\n❌ Test release creation failed")
        sys.exit(1) 